blank_issues_enabled: false
contact_links:
    - name: Ask a Question
      url: https://github.com/SixLabors/ImageSharp.Web/discussions/new?category=q-a
      about: Ask a question about this project.
    - name: Feature Request
      url: https://github.com/SixLabors/ImageSharp.Web/discussions/new?category=show-and-tell
      about: Share ideas for new features for this project.
